package mx.edu.tecnm.itcm.gui;

import java.text.SimpleDateFormat;

/**
 *
 * @author Manuel Avila
 */
public class CreateProject extends javax.swing.JFrame {

    /**
     * Creates new form CreateProject
     */
    public CreateProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCenter = new javax.swing.JPanel();
        labelStartDate = new javax.swing.JLabel();
        dateChooserStartDate = new com.toedter.calendar.JDateChooser();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(60, 0), new java.awt.Dimension(50, 0), new java.awt.Dimension(60, 32767));
        labelFinishDate = new javax.swing.JLabel();
        dateChooserFinishDate = new com.toedter.calendar.JDateChooser();
        labelDescription = new javax.swing.JLabel();
        scrollPaneDescription = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        buttonCreateProject = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        panelFirst = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 0), new java.awt.Dimension(225, 0), new java.awt.Dimension(50, 32767));
        textFieldName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create project");
        setMinimumSize(new java.awt.Dimension(600, 600));
        setPreferredSize(new java.awt.Dimension(640, 640));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        panelCenter.setPreferredSize(new java.awt.Dimension(800, 100));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 5, 20);
        flowLayout1.setAlignOnBaseline(true);
        panelCenter.setLayout(flowLayout1);

        labelStartDate.setText("Start date: ");
        panelCenter.add(labelStartDate);

        dateChooserStartDate.setPreferredSize(new java.awt.Dimension(200, 30));
        panelCenter.add(dateChooserStartDate);
        panelCenter.add(filler1);

        labelFinishDate.setText("Finish date: ");
        panelCenter.add(labelFinishDate);

        dateChooserFinishDate.setPreferredSize(new java.awt.Dimension(200, 30));
        panelCenter.add(dateChooserFinishDate);

        labelDescription.setText("Description: ");
        panelCenter.add(labelDescription);

        scrollPaneDescription.setPreferredSize(new java.awt.Dimension(500, 200));

        textAreaDescription.setColumns(20);
        textAreaDescription.setRows(5);
        textAreaDescription.setPreferredSize(new java.awt.Dimension(500, 300));
        scrollPaneDescription.setViewportView(textAreaDescription);

        panelCenter.add(scrollPaneDescription);

        buttonCreateProject.setText("Create");
        buttonCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateProjectActionPerformed(evt);
            }
        });
        panelCenter.add(buttonCreateProject);

        buttonCancel.setText("Cancelar");
        panelCenter.add(buttonCancel);

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        panelFirst.setPreferredSize(new java.awt.Dimension(50, 100));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 10);
        flowLayout2.setAlignOnBaseline(true);
        panelFirst.setLayout(flowLayout2);

        labelName.setText("Project name: ");
        panelFirst.add(labelName);
        panelFirst.add(filler3);

        textFieldName.setPreferredSize(new java.awt.Dimension(300, 30));
        panelFirst.add(textFieldName);

        getContentPane().add(panelFirst, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateProjectActionPerformed
        String fecha;
        java.util.Date date = new java.util.Date();
        SimpleDateFormat simpleFormat = new SimpleDateFormat("yyyy-MM-dd");
        fecha = simpleFormat.format(dateChooserStartDate.getDate());
    }//GEN-LAST:event_buttonCreateProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCreateProject;
    private com.toedter.calendar.JDateChooser dateChooserFinishDate;
    private com.toedter.calendar.JDateChooser dateChooserStartDate;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelFinishDate;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelStartDate;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelFirst;
    private javax.swing.JScrollPane scrollPaneDescription;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JTextField textFieldName;
    // End of variables declaration//GEN-END:variables
}
